apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx  # nginx-deployment와 연결되는 파드를 찾습니다.
  ports:
    - protocol: TCP
      port: 80       # 외부에서 접근할 포트
      targetPort: 80  # 파드의 컨테이너 포트
  type: LoadBalancer  # 외부에서 접근 가능하게 설정
